controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    controller: App\Controller\AuthController::login

api_login1:
    path: /api/login1
    controller: App\Controller\AuthController::login1

api_signup:
    path: /api/signup
    controller: App\Controller\AuthController::signup

api_verify:
    path: /api/verify
    controller: App\Controller\AuthController::verify

api_verificationProcess:
    path: /api/verificationProcess
    controller: App\Controller\AuthController::verificationProcess