controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    controller: App\Controller\AuthController::login

api_signup:
    path: /api/signup
    controller: App\Controller\AuthController::signup

api_verify:
    path: /api/verify
    controller: App\Controller\AuthController::verify

api_verificationProcess:
    path: /api/verificationProcess
    controller: App\Controller\AuthController::verificationProcess
api_user:
    path: /api/user
    controller: App\Controller\UserController::user