controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    controller: App\Controller\AuthController::login

api_login1:
    path: /api/login1
    controller: App\Controller\AuthController::login1

homePage_getAllPosts:
    path: /homepage/getAllPosts
    controller: App\Controller\HomePageController::getAllPosts
homePage_addPost:
    path: /homepage/addPost
    controller: App\Controller\HomePageController::addPost
homePage_addComment:
    path: /homepage/addComment
    controller: App\Controller\HomePageController::addComment