nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true

        '^/admin_api/':
            allow_origin: [ 'http://localhost:8080' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            max_age: 3600

            allow_credentials: true  # Set allow_credentials to true

        '^/homepage/':
            allow_origin: [ 'http://localhost:8080' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            max_age: 3600
            allow_credentials: true  # Set allow_credentials to true

