nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/admin_api/':
            allow_origin: [ 'http://localhost:8080' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            max_age: 3600